### ISSUE TITLE
This link was generated for another IP address. Try previous step again.

### ISSUE THREAD

**Issue by whitsey** [ivankrastev26/pcloud-php-sdk#15]
What does that even mean?

I uploaded a file, got the link, emailed it to an email address, clicked the link:

`This link was generated for another IP address. Try previous step again.`

**Comment by sich** [comment]
You can't generate direct download links, they are lockd by IP.
Working with files is supposed to happen only by the owner of the file. When you want to share files or folders you have to use "Invite to folder", "Download link" or "Public folder". More information about the later you can find here: https://www.pcloud.com/help/general-help-center/what-is-the-public-folder

**Comment by whitsey** [comment]
What is the purpose of getLink() in your SDK then?
If I can generate a link but not actually use it... What is its purpose?

**Comment by terablade2001** [comment]
According to the help of PCloud:
- _Shared links - send files to friends and family by generating a link. Your recipients will get an instant preview from their browser, even if they don't have a pCloud account. For extra security, you can protect your links with a password or set an expiration date._

I am trying to view a PDF from the 'Shared link' I got, and get that message!
It neither previews the PDF file. Just shows a PDF icon and it's name. No access from the URL - even if I am logged in from my account!
This doesn't make any sense!!
Is it a bug or something?

And no, I don't want to use public folder, because I noticed it creates URLs which can be edited and lead to the root folder from where someone can see any shared file; not just the one I want him to see it via a URL.
