### ISSUE TITLE
Invalid 'access_token' provided.

### ISSUE THREAD

**Issue by denilsonc** [ivankrastev26/pcloud-php-sdk#19]
I am not able to find the access_token! I can only find Client ID and Client secret at https://docs.pcloud.com/my_apps/

**Comment by pollux1er** [comment]
According to my own experience, you need both to get the access token

**Comment by theroot79** [comment]
Hello @denilsonc 
Please, follow the steps below in order to generate working/valid access_token:

. Register app at: https://docs.pcloud.com/my_apps/
      You will receive: "Client ID" and "Client secret"

. Call: $codeUrl = $pCloudApp->getAuthorizeCodeUrl(); 
      This will generate oauth2 link, by clicking on the link you will receive "access code".
      
. Call only once: $accessToken = $pCloudApp->getTokenFromCode($accessCode, $locationID); 
      This will provide you with "Access token" you are asking for, for location ID: "1" is for USA ( if your account is in USA ) , "2" is for Europe. 

. Call the API procedures by setting:
      $pCloudApp->setAppKey($clientId);
      $pCloudApp->setAppSecret($clientSecret);
      $pCloudApp->setLocationId($locationID);
      $pCloudApp->setAccessToken($accessToken);
